package ui;
import javafx.beans.property.SimpleObjectProperty; import javafx.collections.FXCollections; import javafx.geometry.Insets; import javafx.scene.control.*; import javafx.scene.layout.*; import model.*; import service.*; import java.time.LocalDate;
/** Read-only searchable borrowing history backed by BorrowService. */
public class BorrowRecordView extends BorderPane {
 private final BookService books; private final MemberService members; private final BorrowService service; private final TableView<BorrowRecord> table=new TableView<>(); private final TextField search=new TextField(); private final ComboBox<String> filter=new ComboBox<>();
 public BorrowRecordView(BookService books,MemberService members,BorrowService service){this.books=books;this.members=members;this.service=service;getStyleClass().add("page-content");setPadding(new Insets(26));Label title=new Label("Borrow Records");title.getStyleClass().add("page-title");Label description=new Label("Complete transaction history");description.getStyleClass().add("muted-text");HBox summary=new HBox(12,metric("Total",service.getBorrowRecords().size(),"#171923"),metric("Borrowed",count("Borrowed"),"#3478df"),metric("Returned",count("Returned"),"#15966f"),metric("Overdue",count("Overdue"),"#df484e"));search.setPromptText("⌕   Search records...");search.getStyleClass().add("search-field");search.textProperty().addListener((o,a,b)->refresh());filter.setItems(FXCollections.observableArrayList("All statuses","Borrowed","Returned","Overdue"));filter.setValue("All statuses");filter.setOnAction(e->refresh());HBox tools=new HBox(10,search,filter);HBox.setHgrow(search,Priority.ALWAYS);VBox top=new VBox(16,new VBox(5,title,description),summary,tools);setTop(top);BorderPane.setMargin(top,new Insets(0,0,18,0));setup();setCenter(table);refresh();}
 private long count(String wanted){return service.getBorrowRecords().stream().filter(r->status(r).equals(wanted)).count();}
 private VBox metric(String label,long count,String color){Label n=new Label(String.valueOf(count));n.setStyle("-fx-text-fill: "+color+"; -fx-font-size: 22px; -fx-font-weight: bold;");Label t=new Label(label);t.getStyleClass().add("muted-text");VBox b=new VBox(3,n,t);b.getStyleClass().add("stat-card");b.setPadding(new Insets(10,16,10,16));return b;}
 private void setup(){table.getStyleClass().add("data-table");table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.getColumns().addAll(col("Record ID",BorrowRecord::getRecordId),col("Book",r->bookName(r.getBookId())),col("Member",r->memberName(r.getMemberId())),col("Borrow date",BorrowRecord::getBorrowDate),col("Due date",BorrowRecord::getReturnDate),col("Status",this::status));table.setPlaceholder(new Label("No borrow records match the current filters."));}
 private <T> TableColumn<BorrowRecord,T> col(String n,java.util.function.Function<BorrowRecord,T> f){TableColumn<BorrowRecord,T> c=new TableColumn<>(n);c.setCellValueFactory(v->new SimpleObjectProperty<>(f.apply(v.getValue())));return c;} private String bookName(int id){Book b=books.searchBookById(id);return b==null?"Book #"+id:b.getTitle();} private String memberName(int id){Member m=members.searchMemberById(id);return m==null?"Member #"+id:m.getName();}
 private String status(BorrowRecord r){if(r.isReturned())return "Returned";try{return LocalDate.parse(r.getReturnDate()).isBefore(LocalDate.now())?"Overdue":"Borrowed";}catch(Exception e){return "Borrowed";}} private void refresh(){String q=search.getText().trim().toLowerCase(),f=filter.getValue();table.setItems(FXCollections.observableArrayList(service.getBorrowRecords().stream().filter(r->{String joined=(r.getRecordId()+" "+bookName(r.getBookId())+" "+memberName(r.getMemberId())).toLowerCase();return(q.isEmpty()||joined.contains(q))&&("All statuses".equals(f)||status(r).equals(f));}).toList()));}
}
