package ui;
import javafx.beans.property.SimpleObjectProperty; import javafx.collections.FXCollections; import javafx.geometry.Insets; import javafx.scene.control.*; import javafx.scene.layout.*; import model.*; import service.*; import java.time.LocalDate;
/** Read-only searchable borrowing history backed by BorrowService. */
public class BorrowRecordView extends BorderPane {
 private final BookService books; private final MemberService members; private final BorrowService service; private final TableView<BorrowRecord> table=new TableView<>(); private final TextField search=new TextField(); private final ComboBox<String> filter=new ComboBox<>();
 public BorrowRecordView(BookService books,MemberService members,BorrowService service){this.books=books;this.members=members;this.service=service;getStyleClass().add("page-content");setPadding(new Insets(26));search.setPromptText("Search records, books, or members");search.getStyleClass().add("search-field");search.textProperty().addListener((o,a,b)->refresh());filter.setItems(FXCollections.observableArrayList("All statuses","Active","Returned","Overdue"));filter.setValue("All statuses");filter.setOnAction(e->refresh());HBox tools=new HBox(10,search,filter);HBox.setHgrow(search,Priority.ALWAYS);setTop(tools);BorderPane.setMargin(tools,new Insets(0,0,18,0));setup();setCenter(table);refresh();}
 private void setup(){table.getStyleClass().add("data-table");table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.getColumns().addAll(col("Record ID",BorrowRecord::getRecordId),col("Book",r->bookName(r.getBookId())),col("Member",r->memberName(r.getMemberId())),col("Borrow date",BorrowRecord::getBorrowDate),col("Due date",BorrowRecord::getReturnDate),col("Status",this::status));table.setPlaceholder(new Label("No borrow records match the current filters."));}
 private <T> TableColumn<BorrowRecord,T> col(String n,java.util.function.Function<BorrowRecord,T> f){TableColumn<BorrowRecord,T> c=new TableColumn<>(n);c.setCellValueFactory(v->new SimpleObjectProperty<>(f.apply(v.getValue())));return c;} private String bookName(int id){Book b=books.searchBookById(id);return b==null?"Book #"+id:b.getTitle();} private String memberName(int id){Member m=members.searchMemberById(id);return m==null?"Member #"+id:m.getName();}
 private String status(BorrowRecord r){if(r.isReturned())return "Returned";try{return LocalDate.parse(r.getReturnDate()).isBefore(LocalDate.now())?"Overdue":"Active";}catch(Exception e){return "Active";}} private void refresh(){String q=search.getText().trim().toLowerCase(),f=filter.getValue();table.setItems(FXCollections.observableArrayList(service.getBorrowRecords().stream().filter(r->{String joined=(r.getRecordId()+" "+bookName(r.getBookId())+" "+memberName(r.getMemberId())).toLowerCase();return(q.isEmpty()||joined.contains(q))&&("All statuses".equals(f)||status(r).equals(f));}).toList()));}
}
