package ui;

import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import model.Book;
import model.BorrowRecord;
import model.Member;
import service.BookService;
import service.BorrowService;
import service.MemberService;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class BorrowView extends BorderPane {
    private final BookService books; private final MemberService members; private final BorrowService service; private final TableView<BorrowRecord> table=new TableView<>();
    private final TextField recordId=new TextField(), search=new TextField(); private final ComboBox<Book> book=new ComboBox<>(); private final ComboBox<Member> member=new ComboBox<>(); private final DatePicker borrowDate=new DatePicker(LocalDate.now()), returnDate=new DatePicker();
    public BorrowView(BookService books, MemberService members, BorrowService service, boolean recordsOnly, Runnable onChange) {
        this.books=books;this.members=members;this.service=service;setPadding(new Insets(28));getStyleClass().add("content"); Label heading=new Label("Borrow & Return");heading.getStyleClass().add("page-title");Label subtitle=new Label("Process book lending and returns");subtitle.getStyleClass().add("muted-text");
        table.getColumns().addAll(column("Record ID",BorrowRecord::getRecordId),column("Book ID",BorrowRecord::getBookId),column("Member ID",BorrowRecord::getMemberId),column("Borrow date",BorrowRecord::getBorrowDate),column("Return date",BorrowRecord::getReturnDate),column("Status",r->r.isReturned()?"Returned":"Borrowed"));table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);table.setPlaceholder(new Label("No borrow records yet."));table.getSelectionModel().selectedItemProperty().addListener((o,old,r)->{if(r!=null)recordId.setText(String.valueOf(r.getRecordId()));});setCenter(table);
        if(!recordsOnly){VBox left=borrowPanel();VBox right=returnPanel();HBox panels=new HBox(18,left,right);HBox.setHgrow(left,Priority.ALWAYS);HBox.setHgrow(right,Priority.ALWAYS);VBox content=new VBox(18,new VBox(5,heading,subtitle),panels);setCenter(content);}else{setTop(new VBox(14,heading,subtitle));setCenter(table);} refresh();
    }
    private VBox borrowPanel() { book.setItems(FXCollections.observableArrayList(books.getBooks()));member.setItems(FXCollections.observableArrayList(members.getMembers()));book.setPromptText("Choose a book...");member.setPromptText("Choose a member...");book.setConverter(new javafx.util.StringConverter<>(){public String toString(Book b){return b==null?"":b.getId()+" — "+b.getTitle()+" ("+b.getQuantity()+" available)";}public Book fromString(String s){return null;}});member.setConverter(new javafx.util.StringConverter<>(){public String toString(Member m){return m==null?"":m.getId()+" — "+m.getName();}public Member fromString(String s){return null;}});GridPane g=new GridPane();g.setHgap(12);g.setVgap(9);field(g,"Record ID",recordId,0);combo(g,"Member",member,1);combo(g,"Book",book,2);date(g,"Borrow date",borrowDate,3);date(g,"Due date",returnDate,4);Button borrow=new Button("Confirm Borrow");borrow.setMaxWidth(Double.MAX_VALUE);borrow.setOnAction(e->{if(borrow()){UiSupport.info("Book borrowed","Borrow record created successfully.");}});VBox panel=new VBox(14,new Label("Borrow a Book"),muted("Issue a book to a member"),new Separator(),g,borrow);panel.getStyleClass().add("form-panel");panel.setMinWidth(360);return panel; }
    private VBox returnPanel() {search.setPromptText("Record ID or member name...");search.textProperty().addListener((o,a,b)->refresh());table.setPrefHeight(360);Button returned=new Button("Return Selected Book");returned.setMaxWidth(Double.MAX_VALUE);returned.setOnAction(e->{BorrowRecord selected=table.getSelectionModel().getSelectedItem();Integer id=selected==null?UiSupport.positiveId(recordId,"Record ID"):selected.getRecordId();if(id!=null){if(service.returnBook(id,books)){UiSupport.info("Book returned","The book has been returned.");refresh();}else UiSupport.warning("Unable to return","Select an active record; the book and record must exist.");}});VBox panel=new VBox(12,new Label("Return a Book"),muted("Process an incoming return"),new Separator(),search,table,returned);panel.getStyleClass().add("form-panel");panel.setMinWidth(360);VBox.setVgrow(table,Priority.ALWAYS);return panel;}
    private Label muted(String text){Label l=new Label(text);l.getStyleClass().add("muted-text");return l;}
    private boolean borrow(){if(!UiSupport.textPresent(recordId)||book.getValue()==null||member.getValue()==null||borrowDate.getValue()==null||returnDate.getValue()==null){UiSupport.warning("Missing information","Complete the record, book, member, and date fields.");return false;}Integer id=UiSupport.positiveId(recordId,"Record ID");if(id==null)return false;if(returnDate.getValue().isBefore(borrowDate.getValue())){UiSupport.warning("Invalid dates","Expected return must be on or after the borrow date.");return false;}BorrowRecord r=new BorrowRecord(id,book.getValue().getId(),member.getValue().getId(),borrowDate.getValue().format(DateTimeFormatter.ISO_LOCAL_DATE),returnDate.getValue().format(DateTimeFormatter.ISO_LOCAL_DATE),false);if(!service.borrowBook(r,books,members)){UiSupport.warning("Unable to borrow","Check that the record ID is new and the selected book is available.");return false;}refresh();clear();return true;}
    private <T> TableColumn<BorrowRecord,T> column(String name,java.util.function.Function<BorrowRecord,T> f){TableColumn<BorrowRecord,T> c=new TableColumn<>(name);c.setCellValueFactory(d->new javafx.beans.property.SimpleObjectProperty<>(f.apply(d.getValue())));return c;}
    private void field(GridPane g,String s,TextField f,int r){g.add(new Label(s),0,r*2);g.add(f,0,r*2+1);}private void combo(GridPane g,String s,ComboBox<?> c,int r){g.add(new Label(s),0,r*2);g.add(c,0,r*2+1);}private void date(GridPane g,String s,DatePicker d,int r){g.add(new Label(s),0,r*2);g.add(d,0,r*2+1);}
    private void refresh(){String q=search.getText().trim().toLowerCase();table.setItems(FXCollections.observableArrayList(service.getBorrowRecords().stream().filter(r->{Book b=books.searchBookById(r.getBookId());Member m=members.searchMemberById(r.getMemberId());return q.isEmpty()||String.valueOf(r.getRecordId()).contains(q)||String.valueOf(r.getBookId()).contains(q)||String.valueOf(r.getMemberId()).contains(q)||(b!=null&&b.getTitle().toLowerCase().contains(q))||(m!=null&&m.getName().toLowerCase().contains(q));}).toList()));}
    private void clear(){recordId.clear();book.setValue(null);member.setValue(null);borrowDate.setValue(LocalDate.now());returnDate.setValue(null);table.getSelectionModel().clearSelection();}
}
