package ui;
import javafx.geometry.Insets; import javafx.scene.Node; import javafx.scene.chart.*; import javafx.scene.control.*; import javafx.scene.layout.*; import model.*; import service.*; import java.time.LocalDate; import java.util.List;
/** Live dashboard. Every figure is derived from the current services. */
public class DashboardView extends ScrollPane {
 private final BookService books; private final MemberService members; private final BorrowService borrows;
 public DashboardView(BookService books,MemberService members,BorrowService borrows,Runnable openBooks,Runnable openMembers,Runnable openBorrow){this.books=books;this.members=members;this.borrows=borrows;VBox body=new VBox(22);body.setPadding(new Insets(26));body.getStyleClass().add("page-content");HBox cards=new HBox(16,stat("▣","Total books",books.totalBooks(),"Titles in catalog"),stat("♙","Total members",members.totalMembers(),"Registered patrons"),stat("↗","Currently borrowed",active(),"Active loan records"),stat("!","Overdue books",overdue(),"Past their due date"));cards.getChildren().forEach(n->HBox.setHgrow(n,Priority.ALWAYS));HBox quick=new HBox(10,button("Manage books",openBooks),button("Add member",openMembers),button("Borrow a book",openBorrow));VBox activity=new VBox(10,section("BORROWING ACTIVITY"),chart());activity.getStyleClass().add("panel");HBox lower=new HBox(18,popular(),recent());HBox.setHgrow(lower.getChildren().get(0),Priority.ALWAYS);HBox.setHgrow(lower.getChildren().get(1),Priority.ALWAYS);body.getChildren().addAll(cards,quick,activity,lower,overduePanel());setContent(body);setFitToWidth(true);setHbarPolicy(ScrollBarPolicy.NEVER);}
 private VBox stat(String icon,String title,int value,String hint){Label i=new Label(icon);i.getStyleClass().add("stat-icon");Label t=new Label(title);t.getStyleClass().add("stat-title");Label v=new Label(String.valueOf(value));v.getStyleClass().add("stat-value");Label h=muted(hint);VBox b=new VBox(6,i,t,v,h);b.getStyleClass().add("stat-card");b.setMaxWidth(Double.MAX_VALUE);return b;} private Button button(String text,Runnable r){Button b=new Button(text);b.getStyleClass().add("primary-button");b.setOnAction(e->r.run());return b;} private Label section(String s){Label l=new Label(s);l.getStyleClass().add("section-caption");return l;}
 private Node chart(){CategoryAxis x=new CategoryAxis();NumberAxis y=new NumberAxis();BarChart<String,Number> c=new BarChart<>(x,y);c.setLegendVisible(false);c.setAnimated(false);c.setPrefHeight(220);XYChart.Series<String,Number> series=new XYChart.Series<>();series.getData().add(new XYChart.Data<>("Borrowed",active()));series.getData().add(new XYChart.Data<>("Returned",(int)borrows.getBorrowRecords().stream().filter(BorrowRecord::isReturned).count()));series.getData().add(new XYChart.Data<>("Overdue",overdue()));c.getData().add(series);return c;}
 private VBox popular(){VBox box=new VBox(12,section("BOOK CATALOG"));box.getStyleClass().add("panel");if(books.getBooks().isEmpty())box.getChildren().add(muted("No books yet. Add titles to start building your catalog."));else books.getBooks().stream().limit(4).forEach(b->{Label cover=new Label("▣");cover.getStyleClass().add("book-cover");Label title=new Label(b.getTitle());title.getStyleClass().add("row-title");VBox text=new VBox(2,title,muted(b.getAuthor()+" · "+b.getQuantity()+" available"));box.getChildren().add(new HBox(10,cover,text));});return box;} private VBox recent(){VBox box=new VBox(12,section("RECENT BORROWING ACTIVITY"));box.getStyleClass().add("panel");if(borrows.getBorrowRecords().isEmpty())box.getChildren().add(muted("No borrowing activity yet."));else borrows.getRecentBorrowRecords(4).forEach(r->{Label title=new Label("Record #"+r.getRecordId());title.getStyleClass().add("row-title");box.getChildren().add(new VBox(2,title,muted(book(r.getBookId())+" · "+status(r))));});return box;}
 private VBox overduePanel(){VBox box=new VBox(12,section("OVERDUE BOOKS"));box.getStyleClass().add("panel");List<BorrowRecord> list=borrows.getBorrowRecords().stream().filter(r->"Overdue".equals(status(r))).toList();if(list.isEmpty())box.getChildren().add(muted("No overdue books right now."));else list.forEach(r->{Label line=new Label(book(r.getBookId())+" · "+member(r.getMemberId())+" · due "+r.getReturnDate());line.getStyleClass().add("overdue-line");box.getChildren().add(line);});return box;} private Label muted(String s){Label l=new Label(s);l.getStyleClass().add("muted-text");return l;} private int active(){return(int)borrows.getBorrowRecords().stream().filter(r->!r.isReturned()).count();} private int overdue(){return(int)borrows.getBorrowRecords().stream().filter(r->"Overdue".equals(status(r))).count();}private String status(BorrowRecord r){if(r.isReturned())return"Returned";try{return LocalDate.parse(r.getReturnDate()).isBefore(LocalDate.now())?"Overdue":"Active";}catch(Exception e){return"Active";}}private String book(int id){Book b=books.searchBookById(id);return b==null?"Book #"+id:b.getTitle();}private String member(int id){Member m=members.searchMemberById(id);return m==null?"Member #"+id:m.getName();}
}
