package ui;
import javafx.geometry.*; import javafx.scene.Node; import javafx.scene.control.*; import javafx.scene.layout.*; import service.*; import java.util.*; import java.util.prefs.Preferences;
/** Persistent desktop shell; each page receives the existing service instances. */
public class MainLayout extends BorderPane {
 private final BookService books; private final MemberService members; private final BorrowService borrows; private final BorderPane page=new BorderPane(); private final VBox sidebar=new VBox(7); private final Label pageTitle=new Label(),pageSubtitle=new Label(); private final Map<String,Button> nav=new LinkedHashMap<>(); private boolean collapsed; private final Preferences preferences=Preferences.userNodeForPackage(MainLayout.class);
 public MainLayout(BookService books,MemberService members,BorrowService borrows){this.books=books;this.members=members;this.borrows=borrows;getStyleClass().add("app-root");setLeft(sidebar());setTop(header());setCenter(page);if(preferences.getBoolean("darkTheme",false))getStyleClass().add("dark");navigate("Dashboard");}
 private Node header(){pageTitle.getStyleClass().add("header-title");pageSubtitle.getStyleClass().add("header-subtitle");VBox labels=new VBox(3,pageTitle,pageSubtitle);Region gap=new Region();HBox.setHgrow(gap,Priority.ALWAYS);Button bell=new Button("♧"),theme=new Button("◐");bell.getStyleClass().add("icon-button");bell.setTooltip(new Tooltip("Overdue loan notifications"));bell.setOnAction(e->showOverdueNotifications());theme.getStyleClass().add("icon-button");theme.setTooltip(new Tooltip("Toggle light/dark theme"));theme.setOnAction(e->toggleTheme());Label avatar=new Label("LA");avatar.getStyleClass().add("avatar");VBox profile=new VBox(new Label("Library Admin"),new Label("Administrator"));profile.getStyleClass().add("profile-text");HBox h=new HBox(16,labels,gap,bell,theme,avatar,profile);h.setAlignment(Pos.CENTER_LEFT);h.setPadding(new Insets(17,28,17,28));h.getStyleClass().add("top-header");return h;}
 private Node sidebar(){sidebar.getStyleClass().add("sidebar");sidebar.setPadding(new Insets(20,12,18,12));Label mark=new Label("▰");mark.getStyleClass().add("brand-mark");Label name=new Label("Smart Library");name.getStyleClass().add("brand-name");Label sub=new Label("MANAGEMENT SYSTEM");sub.getStyleClass().add("brand-subtitle");VBox wordmark=new VBox(1,name,sub);wordmark.getStyleClass().add("wordmark");Button collapseButton=new Button("‹");collapseButton.getStyleClass().add("collapse-button");collapseButton.setOnAction(e->collapse(!collapsed));Region gap=new Region();HBox.setHgrow(gap,Priority.ALWAYS);HBox brand=new HBox(10,mark,wordmark,gap,collapseButton);brand.setAlignment(Pos.CENTER_LEFT);Label main=caption("MAIN"),other=caption("OTHER");addNav("Dashboard","⌂");addNav("Books","▣");addNav("Members","♙");addNav("Borrow & Return","↔");addNav("Borrow Records","☷");addNav("Settings","⚙");Region push=new Region();VBox.setVgrow(push,Priority.ALWAYS);Label icon=new Label("●");icon.getStyleClass().add("admin-icon");VBox adminText=new VBox(new Label("Library Administrator"),new Label("Signed in"));adminText.getStyleClass().add("admin-text");HBox admin=new HBox(10,icon,adminText);admin.getStyleClass().add("admin-area");sidebar.getChildren().addAll(brand,main,nav.get("Dashboard"),nav.get("Books"),nav.get("Members"),nav.get("Borrow & Return"),nav.get("Borrow Records"),other,nav.get("Settings"),push,admin);return sidebar;}
 private Label caption(String s){Label l=new Label(s);l.getStyleClass().add("nav-caption");return l;} private void addNav(String title,String icon){Button b=new Button(icon+"  "+title);b.setUserData(new String[]{icon,title});b.setMaxWidth(Double.MAX_VALUE);b.getStyleClass().add("sidebar-item");b.setOnAction(e->navigate(title));nav.put(title,b);}
 private void navigate(String title){String sub;Node v;switch(title){case "Books"-> {sub="Manage your book catalog and availability";v=new BookView(books,this::refresh);}case "Members"->{sub="Manage library members and their details";v=new MemberView(members,this::refresh);}case "Borrow & Return"->{sub="Lend books and process returns";v=new BorrowView(books,members,borrows,false,this::refresh);}case "Borrow Records"->{sub="Review borrowing history and status";v=new BorrowRecordView(books,members,borrows);}case "Settings"->{sub="Personalize your workspace";v=new SettingsView(this::toggleTheme,()->getStyleClass().contains("dark"));}default->{title="Dashboard";sub="A live overview of your library";v=new DashboardView(books,members,borrows,()->navigate("Books"),()->navigate("Members"),()->navigate("Borrow & Return"));}}pageTitle.setText(title);pageSubtitle.setText(sub);page.setCenter(v);nav.values().forEach(b->b.getStyleClass().remove("sidebar-item-active"));nav.get(title).getStyleClass().add("sidebar-item-active");}
 private void showOverdueNotifications(){var overdue=borrows.getBorrowRecords().stream().filter(r->{if(r.isReturned())return false;try{return java.time.LocalDate.parse(r.getReturnDate()).isBefore(java.time.LocalDate.now());}catch(RuntimeException ex){return false;}}).toList();String message=overdue.isEmpty()?"There are no overdue loans.":overdue.size()+" overdue loan(s):\n"+overdue.stream().limit(8).map(r->{var b=books.searchBookById(r.getBookId());var m=members.searchMemberById(r.getMemberId());return "• "+(m==null?"Member #"+r.getMemberId():m.getName())+" — "+(b==null?"Book #"+r.getBookId():b.getTitle())+", due "+r.getReturnDate();}).collect(java.util.stream.Collectors.joining("\n"));Alert alert=new Alert(Alert.AlertType.INFORMATION,message,ButtonType.OK);alert.setTitle("Overdue loans");alert.setHeaderText("Library notifications");alert.showAndWait();} private void refresh(){navigate(pageTitle.getText());} private void collapse(boolean value){collapsed=value;if(value)sidebar.getStyleClass().add("sidebar-collapsed");else sidebar.getStyleClass().remove("sidebar-collapsed");nav.values().forEach(b->{String[]d=(String[])b.getUserData();b.setText(value?d[0]:d[0]+"  "+d[1]);b.setTooltip(value?new Tooltip(d[1]):null);});} private void toggleTheme(){boolean dark=getStyleClass().contains("dark");if(dark)getStyleClass().remove("dark");else getStyleClass().add("dark");preferences.putBoolean("darkTheme",!dark);}
}
